version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      # MYSQL_USER: root
      # MYSQL_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    restart: always
  backend:
    container_name: backend
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mysql
    restart : always